name: PR Build
on: pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]sx?') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Cache + Install
        uses: bahmutov/npm-install@v1
      - name: Test
        run: npm run test --if-present
      - name: Build
        run: npm run build --if-present
      - name: Export
        run: |
          npm run export
          touch out/.nojekyll
      - name: Touch file to store deploy label.
        run: echo "${{ github.event.pull_request_head.label }}" > ./out/deployLabel
      - name: Touch file to store PR number.
        run: echo "${{ github.event.number }}" > ./out/prNumber
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: builtOutput
          path: out
          retention-days: 1
