name: PR Build
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run build && npm run export && touch out/.nojekyll
      - run: echo ${{ github.event.head }}
      - run: echo "${{ github.event.number }}--${{ github.event.head.label }}" > ./out/deployName
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: builtOutput
          path: out
          retention-days: 1
